
CREATE TABLE IF NOT EXISTS members(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR (50) NOT NULL,
    first_name_jap VARCHAR(50),
    last_name_jap VARCHAR(50),
    first_name_kor VARCHAR(50),
    last_name_kor VARCHAR(50),
    first_name_ch VARCHAR(50),
    last_name_ch VARCHAR(50),
    date_of_birth DATE,
    country_id INTEGER
);

CREATE TABLE IF NOT EXISTS release_groups(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    grouping_id INTEGER NOT NULL,
    type_id INTEGER
);

CREATE TABLE IF NOT EXISTS releases(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(50),
    release_year INTEGER,
    format_id INTEGER,
    country_id INTEGER,
    release_group_id INTEGER NOT NULL,
    annotation VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS groupings(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    type VARCHAR(10) NOT NULL
);

CREATE TABLE IF NOT EXISTS tracks(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(50) NOT NULL,
    title_kor VARCHAR (50),
    title_jap VARCHAR (50),
    featuring VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS countries(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS release_groups_types(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS release_formats(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    format VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS releases_tracks(
    release_id INTEGER NOT NULL,
    track_id INTEGER NOT NULL,
    track_num INTEGER NOT NULL,
    PRIMARY KEY (release_id, track_id)
);

CREATE TABLE IF NOT EXISTS members_groupings(
    member_id INTEGER NOT NULL,
    grouping_id INTEGER NOT NULL,
    PRIMARY KEY (member_id, grouping_id)
);

ALTER TABLE release_groups  
    ADD CONSTRAINT fk_type
    FOREIGN KEY (type_id) REFERENCES release_groups_types(id);

ALTER TABLE release_groups 
    ADD CONSTRAINT fk_unit
    FOREIGN KEY(grouping_id) REFERENCES groupings(id);

ALTER TABLE releases    
    ADD CONSTRAINT fk_format
    FOREIGN KEY (format_id) REFERENCES release_formats(id);

ALTER TABLE releases
    ADD CONSTRAINT fk_country
    FOREIGN KEY (country_id) REFERENCES countries(id);

ALTER TABLE releases
    ADD CONSTRAINT fk_release_group
    FOREIGN KEY (release_group_id) REFERENCES release_groups(id);

ALTER TABLE releases_tracks
    ADD CONSTRAINT fk_releases_tracks_releases
    FOREIGN KEY(release_id) REFERENCES releases(id);

ALTER TABLE releases_tracks
    ADD CONSTRAINT fk_release_tracks_tracks
    FOREIGN KEY(track_id) REFERENCES tracks(id);

ALTER TABLE members_groupings
    ADD CONSTRAINT fk_member
    FOREIGN KEY (member_id) REFERENCES members(id);

ALTER TABLE members_groupings
    ADD CONSTRAINT fk_members_groupings_groupings
    FOREIGN KEY (grouping_id) REFERENCES groupings(id);

ALTER TABLE members
    ADD CONSTRAINT fk_country
    FOREIGN KEY (country_id) REFERENCES countries(id);